language: python
python:
  - 2.7
  - pypy
  - 3.4
  - 3.5
  - 3.6
  - pypy3
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
script: make travis
install:
  - pip install .
  - pip install -r requirements.txt
after_success:
  - coveralls
