language: python
cache: pip
python:
  - 2.7
  - pypy
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3

script: make travis
install:
  - pip install .
  - pip install -r requirements.txt
after_success:
  - coveralls
